---
title: "Milpitas SVI Data Processing"
author: "Tiffany Zhu"
date: "1/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(flexdashboard)
library(tidyverse)
library(leaflet)
library(plotly)
library(sf)
library(tigris)
```

```{r}
# Loading SVI data

ca_svi = read_csv("California.csv")
ca_svi

```

``` {r}
# Filtering to Milpitas data

scc_svi = ca_svi %>%
  filter(COUNTY == "Santa Clara") %>%
  mutate(TRACT = gsub("Census Tract ", "", LOCATION),
         TRACT = gsub(", Santa Clara County, California", "", TRACT))
scc_svi %>% select(TRACT)

milpitas_tracts = c("5044.12",
                    "5044.13",
                    "5044.14",
                    "5044.15",
                    "5044.16",
                    "5044.17",
                    "5044.18",
                    "5044.20",
                    "5044.21",
                    "5044.22",
                    "5045.04",
                    "5045.05",
                    "5045.06",
                    "5045.07",
                    "5046.02",
                    "5050.06")
milpitas_svi = scc_svi %>%
  filter(TRACT %in% milpitas_tracts) %>%
  select(FIPS,
         LOCATION,
         TRACT,
         RPL_THEMES,
         RPL_THEME1,
         RPL_THEME2,
         RPL_THEME3,
         RPL_THEME4)
milpitas_svi

```

```{r}
# Adding geometry info

ca_tracts = tracts("CA", cb = T, progress_bar = F)

milpitas_svi_map = milpitas_svi %>%
                   left_join(ca_tracts %>% select(GEOID),
                             by = c("FIPS" = "GEOID")) %>%
                   st_as_sf()
saveRDS(milpitas_svi_map, file = "milpitas_svi_map.rds")

```

```{r}
# Mapping the SVI data

svi_pal = colorNumeric(palette = "Reds",
                       domain = milpitas_svi_map$RPL_THEMES)

leaflet() %>%
  addTiles() %>%
  addPolygons(data = milpitas_svi_map,
              fillColor = ~svi_pal(RPL_THEMES),
              color = "white",
              opacity = 0.5,
              fillOpacity = 0.8,
              weight = 1,
              label = ~paste0(RPL_THEMES, " in tract ", TRACT),
              highlightOptions = highlightOptions(weight = 2,
                                                  opacity = 1)) %>%
  addLegend(data = milpitas_svi_map,
            pal = svi_pal,
            values = ~RPL_THEMES,
            title = "Social Vulnerability Index, Milpitas")


```

```{r}
# Socioeconomic Theme

svi_pal_se = colorNumeric(palette = "Greens",
                          domain = milpitas_svi_map$RPL_THEME1)

leaflet() %>%
  addTiles() %>%
  addPolygons(data = milpitas_svi_map,
              fillColor = ~svi_pal_se(RPL_THEME1),
              color = "white",
              opacity = 0.5,
              fillOpacity = 0.8,
              weight = 1,
              label = ~paste0(RPL_THEME1, " in tract ", TRACT),
              highlightOptions = highlightOptions(weight = 2,
                                                  opacity = 1)) %>%
  addLegend(data = milpitas_svi_map,
            pal = svi_pal_se,
            values = ~RPL_THEME1,
            title = "Social Vulnerability Index<br>
                     (Socioeconomic Status),<br>
                     Milpitas")


```

```{r}
# Household Composition and Disability Theme

svi_pal_hcd = colorNumeric(palette = "Oranges",
                           domain = milpitas_svi_map$RPL_THEME2)

leaflet() %>%
  addTiles() %>%
  addPolygons(data = milpitas_svi_map,
              fillColor = ~svi_pal_hcd(RPL_THEME2),
              color = "white",
              opacity = 0.5,
              fillOpacity = 0.8,
              weight = 1,
              label = ~paste0(RPL_THEME2, " in tract ", TRACT),
              highlightOptions = highlightOptions(weight = 2,
                                                  opacity = 1)) %>%
  addLegend(data = milpitas_svi_map,
            pal = svi_pal_hcd,
            values = ~RPL_THEME2,
            title = "Social Vulnerability Index<br>
                     (Household Composition<br>
                     and Disability), Milpitas")

```

```{r}
# Minority Status and Language Theme

svi_pal_msl = colorNumeric(palette = "Purples",
                           domain = milpitas_svi_map$RPL_THEME3)

leaflet() %>%
  addTiles() %>%
  addPolygons(data = milpitas_svi_map,
              fillColor = ~svi_pal_msl(RPL_THEME3),
              color = "white",
              opacity = 0.5,
              fillOpacity = 0.8,
              weight = 1,
              label = ~paste0(RPL_THEME3, " in tract ", TRACT),
              highlightOptions = highlightOptions(weight = 2,
                                                  opacity = 1)) %>%
  addLegend(data = milpitas_svi_map,
            pal = svi_pal_msl,
            values = ~RPL_THEME3,
            title = "Social Vulnerability Index<br>
                     (Minority Status and<br>
                     Language), Milpitas")

```

```{r}
# Housing Type and Transportation Theme

svi_pal_htt = colorNumeric(palette = "Blues",
                           domain = milpitas_svi_map$RPL_THEME4)

leaflet() %>%
  addTiles() %>%
  addPolygons(data = milpitas_svi_map,
              fillColor = ~svi_pal_htt(RPL_THEME4),
              color = "white",
              opacity = 0.5,
              fillOpacity = 0.8,
              weight = 1,
              label = ~paste0(RPL_THEME4, " in tract ", TRACT),
              highlightOptions = highlightOptions(weight = 2,
                                                  opacity = 1)) %>%
  addLegend(data = milpitas_svi_map,
            pal = svi_pal_htt,
            values = ~RPL_THEME4,
            title = "Social Vulnerability Index<br>
                     (Housing Type and<br>
                     Transportation), Milpitas")

```


