---
title: "Test File for Assignment 2"
author: "Tiffany Zhu"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Documents/GitHub/tiffanyzhu10.github.io/testfile-asst2")
library(tidyverse)
library(plotly)
library(sf)
library(tigris)
library(leaflet)
library(censusapi)

Sys.setenv(CENSUS_KEY = "5ace7165d1f551af1a6a8876ee3986faa544ea83")

acs_vars_2018_5yr = listCensusMetadata(name = "2018/acs/acs5",
                                       type = "variables")
saveRDS(acs_vars_2018_5yr, "census_vars-test2.rds")
```

# Section 2.1

```{r census, echo=TRUE, message=FALSE, warning=FALSE}
smc_sexbyage = getCensus(name = "acs/acs5",
                         vintage = 2018,
                         region = "block group:*",
                         regionin = "state:06+county:081",
                         vars = "group(B01001)") %>%
               mutate(cbg = paste0(state, county, tract, block_group)) %>%
               select(!c(GEO_ID, state, county,
                         tract, block_group, NAME) &
                      !ends_with(c("EA", "MA", "M"))) %>%
               pivot_longer(ends_with("E"),
                            names_to = "variable",
                            values_to = "estimate") %>%
               left_join(acs_vars_2018_5yr %>% select(name, label),
                         by = c("variable" = "name")) %>%
               select(-variable) %>%
               separate(label,
                        into = c(NA, NA, "sex", "age"),
                        sep = "!!") %>%
               filter(!is.na(age))

smc_elderly = smc_sexbyage %>%
              mutate(elderly = ifelse(
                  age %in% c("65 and 66 years",
                             "67 to 69 years",
                             "70 to 74 years",
                             "75 to 79 years",
                             "80 to 84 years",
                             "85 years and over"),
                  estimate,
                  NA)) %>%
              group_by(cbg) %>%
              summarize(elderly = sum(elderly, na.rm = T),
                        total_pop = sum(estimate, na.rm = T)) %>%
              mutate(percent_elderly = elderly/total_pop*100) %>%
              filter(!is.na(percent_elderly))

smc_blockgroups = block_groups("CA",
                               "San Mateo",
                               cb = T,
                               progress_bar = F)
elderly_pal = colorNumeric(palette = "Blues",
                           domain = smc_elderly$percent_elderly)
leaflet() %>%
  addTiles() %>%
  addPolygons(data = smc_elderly %>%
                     left_join(smc_blockgroups %>% select(GEOID),
                               by = c("cbg" = "GEOID")) %>%
                     st_as_sf() %>%
                     st_transform(4326),
              fillColor = ~elderly_pal (percent_elderly),
              color = "white",
              opacity = 0.5,
              fillOpacity = 0.5,
              weight = 1,
              label = ~paste0(round(percent_elderly),
                              "% over age 65"),
              highlightOptions = highlightOptions(weight = 2,
                                                  opacity = 1)) %>%
  addLegend(data = smc_elderly,
            pal = elderly_pal,
            values = ~percent_elderly,
            title = "% over 65")
```

# Section 2.2

```{r equity, echo=TRUE, message=FALSE, warning=FALSE}

bay_income_white = getCensus(name = "acs/acs5",
                             vintage = 2018,
                             region = "county:001,013,041,055,075,081,085,095,097",
                             regionin = "state:06",
                             vars = "group(B19001A)") %>%
                   select(!c(GEO_ID,state,NAME) &
                          !ends_with(c("EA","MA","M"))) %>%
                   pivot_longer(ends_with("E"),
                                names_to = "variable",
                                values_to = "estimate") %>%
                   left_join(acs_vars_2018_5yr %>% select(name, label),
                         by = c("variable" = "name")) %>%
                   select(-variable) %>%
                   separate(label,
                            into = c(NA, NA, "income"),
                            sep = "!!") %>%
                   filter(!is.na(income))

census_race_labels = c("White Alone",
                       "Black or African American",
                       "American Indian and Alaska Native Alone",
                       "Asian Alone",
                       "Native Hawaiian and Other Pacific Islander Alone)",
                       "Some Other Race Alone",
                       "Two or More Races")
bay_income_race = 1:7 %>%
  map_dfr(function(x) {
    getCensus(name = "acs/acs5",
              vintage = 2018,
              region = "county:001,013,041,055,075,081,085,095,097",
              regionin = "state:06",
              vars = paste0("group(B19001", LETTERS[x], ")")) %>%
    select(!c(GEO_ID, state, NAME) &
           !ends_with(c("EA", "MA", "M"))) %>%
    pivot_longer(ends_with("E"),
                 names_to = "variable",
                 values_to = "estimate") %>%
    left_join(acs_vars_2018_5yr %>% select(name, label),
                                    by = c("variable" = "name")) %>%
    select(-variable) %>%
    separate(label,
             into = c(NA, NA, "income"),
             sep = "!!") %>%
    filter(!is.na(income)) %>%
    mutate(race = census_race_labels[x])
    })

bay_race_total = bay_income_race %>%
                 group_by(race) %>%
                 summarize(estimate = sum(estimate)) %>%
                 mutate(income = "Total")
bay_income_race %>% group_by(income, race) %>%
                    summarize(estimate = sum(estimate)) %>%
                    rbind(bay_race_total) %>%
                    ggplot() +
                    geom_bar(aes(x = income %>%
                                     factor(levels = rev(c("Total",
                                                           bay_income_race$income[1:16]))),
                                 y = estimate,
                                 fill = race),
                             stat = "identity",
                             position = "fill") +
                    labs(x = "Household income",
                         y = "Proportion of households",
                         title = "Bay Area household income by race",
                         fill = "Race of householder") +
                    coord_flip() +
                    theme(legend.position = "bottom",
                          legend.direction = "vertical")

```

Top value is percentage of non-white people overall.
Middle value is percentage of non-white people who make less than $30,000.


```{r equity2, echo=TRUE}
((sum(bay_race_total$estimate[1:6])/sum(bay_race_total$estimate))*100) %>% round()

((bay_income_race %>% filter(income %in% bay_income_race$income[1:5]) %>%
                    filter(race != "White Alone") %>%
                    pull(estimate) %>%
                    sum()) /
  (bay_income_race %>% filter(income %in% bay_income_race$income[1:5]) %>%
                       pull(estimate) %>%
                       sum()) * 100) %>%
  round()

((((bay_income_race %>% filter(income %in% bay_income_race$income[1:5]) %>%
                    filter(race != "White Alone") %>%
                    pull(estimate) %>%
                    sum()) /
  (bay_income_race %>% filter(income %in% bay_income_race$income[1:5]) %>%
                       pull(estimate) %>%
                       sum())) /
  (sum(bay_race_total$estimate[1:6]) / sum(bay_race_total$estimate)) - 1) * 100) %>%
  round()
```

# Section 2.3

``` {r migration1, echo=TRUE}
acs_vars_2019_1yr = listCensusMetadata(name = "2019/acs/acs1", type = "variables")
smc_mobility_current_19 = getCensus(name = "acs/acs1",
                                    vintage = 2019,
                                    region = "county:081",
                                    regionin = "state:06",
                                    vars = c("group(B07010)")) %>%
                          select(!c(GEO_ID, state, NAME) &
                                 !ends_with(c("EA", "MA", "M"))) %>%
                          pivot_longer(ends_with("E"),
                                       names_to = "variable",
                                       values_to = "estimate") %>%
                          left_join(acs_vars_2019_1yr %>% select(name, label),
                                    by = c("variable" = "name")) %>%
                          select(-variable)
smc_mobility_current_19$label
```
``` {r migration2, echo = TRUE}
smc_mobility_current_19 = getCensus(name = "acs/acs1",
                                    vintage = 2019,
                                    region = "county:081",
                                    regionin = "state:06",
                                    vars = c("group(B07010)")) %>%
                          select(!c(GEO_ID, state, NAME) &
                                 !ends_with(c("EA", "MA", "M"))) %>%
                          pivot_longer(ends_with("E"),
                                       names_to = "variable",
                                       values_to = "estimate") %>%
                          left_join(acs_vars_2019_1yr %>% select(name, label),
                                    by = c("variable" = "name")) %>%
                          select(-variable) %>%
                          separate(label,
                                   into = c(NA, NA, "mobility", "temp", "income"),
                                   sep = "!!") %>%
                          mutate(income = ifelse(temp == "No income",
                                                 temp,
                                                 income),
                                 mobility = ifelse(mobility %in% c("Same house 1 year ago:", "Moved within same country"),
                                   "Here since last year",
                                   "Inflow")) %>%
                          filter(!is.na(income)) %>%
                          group_by(mobility, income) %>%
                          summarize(estimate = sum(estimate))

smc_mobility_lastyear_19 = getCensus(name = "acs/acs1",
                                    vintage = 2019,
                                    region = "county:081",
                                    regionin = "state:06",
                                    vars = c("group(B07410)")) %>%
                           select(!c(GEO_ID, state, NAME) &
                                 !ends_with(c("EA", "MA", "M"))) %>%
                           pivot_longer(ends_with("E"),
                                       names_to = "variable",
                                       values_to = "estimate") %>%
                           left_join(acs_vars_2019_1yr %>% select(name, label),
                                    by = c("variable" = "name")) %>%
                           select(-variable) %>%
                           separate(label,
                                    into = c(NA, NA, "mobility", "temp", "income"),
                                    sep = "!!") %>%
                           mutate(income = ifelse(temp == "No income",
                                                  temp,
                                                  income),
                                  mobility = ifelse(mobility %in% c("Same house:", "Moved within same county:"),
                                                    "Here since last year",
                                                    "Outflow")) %>%
                           filter(!is.na(income)) %>%
                           group_by(mobility, income) %>%
                           summarize(estimate = sum(estimate))
smc_mobility_lastyear_19
```
``` {r migration3, echo=TRUE}
smc_mobility_current_18 = getCensus(name = "acs/acs1",
                                    vintage = 2018,
                                    region = "county:081",
                                    regionin = "state:06",
                                    vars = c("group(B07010)")) %>%
                          select(!c(GEO_ID, state, NAME) &
                                 !ends_with(c("EA", "MA", "M"))) %>%
                          pivot_longer(ends_with("E"),
                                       names_to = "variable",
                                       values_to = "estimate") %>%
                          left_join(acs_vars_2019_1yr %>% select(name, label),
                                    by = c("variable" = "name")) %>%
                          select(-variable) %>%
                          separate(label,
                                   into = c(NA, NA, "mobility", "temp", "income"),
                                   sep = "!!") %>%
                          mutate(income = ifelse(temp == "No income",
                                                 temp,
                                                 income),
                                 mobility = "Here last year") %>%
                          filter(!is.na(income)) %>%
                          group_by(mobility, income) %>%
                          summarize(estimate = sum(estimate))

smc_flows_19 <- rbind(smc_mobility_current_18,
                     smc_mobility_lastyear_19 %>%
                       filter(mobility == "Outflow"),
                     smc_mobility_current_19 %>%
                       filter(mobility == "Inflow"),
                     smc_mobility_current_19 %>%
                       group_by(income) %>%
                       summarize(estimate = sum(estimate)) %>%
                       mutate(mobility = "Here this year")) %>%
                     pivot_wider(names_from = mobility,
                                 values_from = estimate) %>%
                     mutate(`External net` = Inflow - Outflow,
                            `Internal net` = `Here this year` - `Here last year` - `External net`,) %>%
                     select(`Income tier` = income,
                            `Internal net`,
                            `External net`,
                            `Here last year`,
                            `Here this year`,
                            Outflow,
                            Inflow)
```

# Section 2.4

``` {r baycounties, echo=TRUE}
ca_counties = counties("CA", cb = T, progress_bar = F)
st_crs(ca_counties)
projection = "+proj=utm +zone=10 +ellps=GRS80 +datum=NAD83 +units=ft +no_defs"
ca_counties_transformed = ca_counties %>% 
                          st_transform(4326) %>% 
                          st_transform(26910) %>% 
                          st_transform(projection) %>% 
                          st_transform(st_crs(ca_counties))

ggplot(ca_counties) + geom_sf()
leaflet() %>% addTiles() %>%
              addPolygons(data = ca_counties %>% 
                                st_transform(4326)) %>%
              addMarkers(data = ca_counties %>%
                                st_centroid() %>%
                                st_transform(4326))

bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )
bay_counties = ca_counties %>% filter(NAME %in% bay_county_names)
```

``` {r microdata1, echo=TRUE}

library(tidycensus)
census_api_key("5ace7165d1f551af1a6a8876ee3986faa544ea83")

pums_vars_2018 = pums_variables %>%
                 filter(year == 2018, survey == "acs5")
pums_vars_2018_distinct_hh = pums_vars_2018 %>%
                             distinct(var_code, var_label, data_type, level) %>%
                             filter(level == "housing")
ca_pums = get_pums(variables = c("PUMA", "NP", "HHL", "HINCP", "TEN"),
                   state = "CA",
                   year = 2018,
                   survey = "acs5",
                   recode = T)
ca_pumas = pumas("CA", cb = T, progress_bar = F)
bay_pumas = ca_pumas %>%
            st_centroid() %>%
            .[bay_counties, ] %>%
            st_set_geometry(NULL) %>%
            left_join(ca_pumas %>% select(GEOID10)) %>%
            st_as_sf()
bay_pums = ca_pums %>%
           filter(PUMA %in% bay_pumas$PUMACE10)
bay_pums_example = bay_pums %>%
                  filter(!duplicated(SERIALNO)) %>%
                  mutate(nonenglish_renter_lowinc = ifelse(
                    (HHL_label != "English only") &
                    (TEN_label == "Rented") &
                    (HINCP < 100000),
                    WGTP,
                    0)) %>%
                  group_by(PUMA) %>%
                  summarize(perc_nonenglish_renter_lowinc = 
                            sum(nonenglish_renter_lowinc, na.rm = T)/sum(WGTP, na.rm = T)*100) %>%
                  left_join(bay_pumas %>% select(PUMACE10),
                                          by = c("PUMA" = "PUMACE10")) %>%
                  st_as_sf()

pums_pal = colorNumeric(palette = "Oranges",
                        domain = bay_pums_example$perc_nonenglish_renter_lowinc)
leaflet() %>%
  addTiles() %>%
  addPolygons(data = bay_pums_example,
              fillColor = ~pums_pal(perc_nonenglish_renter_lowinc),
              color = "white",
              opacity = 0.5,
              fillOpacity = 0.5,
              weight = 1,
              label = ~paste0(round(perc_nonenglish_renter_lowinc),
                              "% non-English-speaking renter households making less than 100K"),
              highlightOptions = highlightOptions(weight = 2, opacity = 1)) %>%
  addLegend(data = bay_pums_example,
            pal = pums_pal,
            values = ~perc_nonenglish_renter_lowinc,
            title = "% non-English-speaking<br>renter households<br>making less than 100K")

```

# Section 2.5

``` {r spatialsubs1, echo = TRUE}
bay_pdas = st_read("https://opendata.arcgis.com/datasets/36dd7a36576f42d4a3d6b0708e3982f4_0.geojson")

smc_blockgroups = block_groups("CA", "San Mateo", cb = T, progress_bar = F) %>%
                  st_transform(st_crs(bay_pdas))
leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(data = bay_pdas,
              stroke = F,
              fillOpacity = 0.5) %>%
  addPolygons(data = smc_blockgroups,
              color = "red",
              weight = 0.75,
              fill = F)
```

``` {r spatialsubs2, echo=TRUE}
smc_pdas = bay_pdas %>%
           filter(county == "San Mateo")
smc_cbg_pop = getCensus(name = "acs/acs5",
                        vintage = 2018,
                        region = "block group:*",
                        regionin = "state:06+county:081",
                        vars = "B01001_001E") %>%
              transmute(cbg = paste0(state, county, tract, block_group),
                        pop = B01001_001E) %>%
              left_join(smc_blockgroups %>% select(GEOID),
                        by = c("cbg" = "GEOID")) %>%
              st_as_sf()
smc_pda_pop1 = smc_cbg_pop[smc_pdas, ]
sum(smc_pda_pop1$pop)
```

``` {r spatialsubs3, echo=TRUE}
leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(data = smc_pdas,
              stroke = F,
              fillOpacity = 0.5) %>%
  addPolygons(data = smc_pda_pop1,
              color = "red",
              weight = 0.75,
              fill = F)
```

``` {r spatialsubs4, echo=T}
smc_pda_pop2 = smc_cbg_pop %>%
               st_centroid() %>%
               .[smc_pdas, ] %>%
               st_set_geometry(NULL) %>%
               left_join(smc_cbg_pop %>% select(cbg)) %>%
               st_as_sf()
sum(smc_pda_pop2$pop)
```

``` {r spatialsubs5, echo=T}
leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(data = smc_pdas,
              stroke = F,
              fillOpacity = 0.5) %>%
  addPolygons(data = smc_pda_pop2,
              color = "red",
              weight = 0.75,
              fill = F)
```

``` {r spatialsubs6, echo = T}
smc_cbg_pop_area <-
  smc_cbg_pop %>% 
  st_transform(26910) %>% 
  mutate(area = st_area(.))

smc_cbg_pop_intersection = smc_cbg_pop_area %>%
                           st_intersection(smc_pdas %>% st_transform(26910))

leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = smc_pdas,
    stroke = F,
    fillOpacity = 0.5
  ) %>% 
  addPolygons(
    data = smc_cbg_pop_intersection %>% 
      st_transform(4326),
    color = "red",
    weight = 0.75,
    fill = F
  )
```

``` {r spatialsubs7, echo = T}
smc_pda_pop3 = smc_cbg_pop %>%
               st_transform(26910) %>%
               mutate(original_area = st_area(.)) %>%
               st_intersection(smc_pdas %>% st_transform(26910)) %>%
               mutate(leftover_area = st_area(.),
                      perc_area = leftover_area / original_area,
                      pop = pop * perc_area)
sum(smc_pda_pop3$pop) %>% round()
```


